### ISSUE TITLE
Python Exception when building document

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-documentation#16]
Hi Holger,

I faced an issue when working with new build jobs for OSD6.
Something failed when building document and below exception occurred:
```
Exception: __init__() should return None, not 'tuple'!
```
I checked and found that it came from the return of ``__init__`` of  ``CMainDocConfig`` class at below code:
https://github.com/test-fullautomation/robotframework-documentation/blob/3c71a72636e29c329e68e25c2b92fd23f8478a0a/maindoc/CMainDocConfig.py#L115

Log on build pipeline for reference:
https://gitlab-apertispro.boschdevcloud.com/robotframework-aio/main/build/-/jobs/1454414

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Holger,

__init__should not return anything as it is a overridden method which is called internally.
https://docs.quantifiedcode.com/python-anti-patterns/correctness/explicit_return_in_init.html

As per 
https://docs.python.org/2/reference/datamodel.html#special-method-names
"none" has to be returned.

please correct.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Solved with:
https://github.com/test-fullautomation/robotframework-documentation/pull/17

**Comment by test-fullautomation** [comment]
merged #17
