### ISSUE TITLE
Ability to specify the included chapter(s) for main document

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-documentation#24]
Hi Holger,
Hi Thomas,

We can specify the library document packages (from repositories) when building Robot Framework AIO now with the `--configfile` argument of genmaindoc.

But I observed that we also need to specify the included chapter(s) (which is required for OSS, which is only internal) in the main document.
For example, I think the chapter **Aptertis** is only required for BIOS version (related to DLT and Aptertis), so that it should be not included in the OSS document.

As the discussion with Holger, the approach can be:
* The distinguish  `RobotFrameworkAIO_Reference.tex` files for BIOS and OSS by cloning this file with other name and update the included chapter(s). The OSS version is the base document and the BIOS version will also include internal chapter(s).
* gendoc tool need to be updated to allow a configuration in `maindoc_config.json` such as **MAINPDFFILENAME** to make sure that only 1 name for generated PDF document.
* The ***.tex** file for BIOS will be configured in the appropriate `maindoc_config.json` (located in **build** repo) for internal build
* The ***.tex** and `maindoc_config.json` for OSS are default files in this repo

Please correct me in case I missed the ideas.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved with already merged #26
