### ISSUE TITLE
Bosch internal release must contain robotframework-qconnect-dlt documentation

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-documentation#25]
for OSS-version removed
https://github.com/test-fullautomation/robotframework-documentation/pull/21

to be checked if Bosch internally available.

**Comment by ngoan1608** [comment]
Hi Thomas,

The document of internal version also contains the dlt library and tmllog2robotlog documents now. The maindoc_config for internal is located in **build** repo which includes these internal repos.

I have checked and they are available in previous built packages 0.6.0.x (for both Windows and OSD).

Please double check it.


Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved with already merged #26
