### ISSUE TITLE
Bundle number adaptions in GenMainDoc

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-documentation#30]
The command line of GenMainDoc has to be extended by the version number and the version date of the entire RobotFramework AIO bundle.

This extension is the replacement for reading the values out of a Python file of the RobotFramework_TestsuitesManagement in a local cloned repository..

If the values are not provided in command line the corresponding fields on the top page of the resulting PDF document will be empty.

**Comment by HolQue** [comment]
Done with

https://github.com/test-fullautomation/robotframework-documentation/pull/32

**Comment by test-fullautomation** [comment]
solved and already merged with #32
