### ISSUE TITLE
generated list of python modules + version which we integrate

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-documentation#37]
We need in our documentation a generated list of python modules + version which we integrate.

_Originally posted by @test-fullautomation in https://github.com/test-fullautomation/RobotFramework_AIO/issues/100#issuecomment-1562906867_

**Comment by HolQue** [comment]
Hi Thomas,

first basic questions:

1. From where to get the names of Python modules to be considered for this list (or any automated parsing based on name patterns)?
2. It's necessary to distinguish between Windows and Linux (or always the same)?

**Comment by test-fullautomation** [comment]
Hi Holger,

1. I think we need to wrap "pip freeze" somehow. This provides the data, but we need to postprocess it in order to bring in in a nice way into our documentation.
2. Yes, the list can be different.

Thank you,
 Thomas
