### ISSUE TITLE
Last chapter "intalled python modules" need info how to add new modules

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-documentation#41]
Last chapter "intalled python modules" need info how to add new modules for Windows as well as Linux.

**Comment by HolQue** [comment]
Done with

https://github.com/test-fullautomation/robotframework-documentation/pull/42

**Comment by test-fullautomation** [comment]
merged #42: open: exact command line for bosch-internal release as copy&paste.

**Comment by HolQue** [comment]
Solved with
https://github.com/test-fullautomation/robotframework-documentation/pull/44
and corresponding maindoc_config_BIOS.json adaption in build repository.

**Comment by test-fullautomation** [comment]
After discussion closed as solved.
