### ISSUE TITLE
DocBuilder failed on Linux due to doc generator GenPackageDoc.py does not exist

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-documentation#5]
Hi,

Below error occurs when running the setup file for this repo on Linux machine
`[CDocBuilder.Build] : The package doc generator '/builds/ntd1hc/python-genpackagedoc/GenPackageDoc.py' does not exist!`

The issue happen because the file name on Linux is case sensitive, so that [the doc generator file name definition](https://github.com/test-fullautomation/robotframework-documentation/blob/fa96b56e9d0302d646e175f4bd80e6dfca420ab9/maindoc/CDocBuilder.py#L326) should be changed to match case with existing file in `python-genpackagedoc` repo
https://github.com/test-fullautomation/python-genpackagedoc/blob/develop/genpackagedoc.py

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Issue is solved.
